# Generated by Django 2.2.11 on 2020-03-25 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationapikey',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='OrganizationAPIKey',
        ),
    ]
