# Generated by Django 2.2.11 on 2020-03-25 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rest_framework_api_key', '0004_prefix_hashed_key'),
        ('apps_api', '0002_auto_20200325_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_key', to='rest_framework_api_key.APIKey')),
            ],
        ),
    ]
