# Generated by Django 2.2.11 on 2020-03-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_api', '0003_apps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='api_key',
            field=models.TextField(),
        ),
    ]
