# Generated by Django 2.2.11 on 2020-03-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_api', '0004_auto_20200325_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='api_key',
            field=models.TextField(blank=True),
        ),
    ]
