# Generated by Django 2.2.11 on 2020-03-26 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps_api', '0005_auto_20200325_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='created_data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
