# Generated by Django 2.2.11 on 2020-03-26 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_api', '0006_apps_created_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apps',
            old_name='created_data',
            new_name='created_date',
        ),
    ]
